### Simple GET call to kick off orchestrator and entity
GET http://localhost:7071/api/orchestrators/DurableFunctionsOrchestratorJS

### Retrive the status
GET http://localhost:7071/runtime/webhooks/durabletask/instances/<PUT YOUR DATA HERE>